### ISSUE TITLE
Large number of non-biallelic SNPs

### ISSUE THREAD

**Issue by bschilder** [Al-Murphy/MungeSumstats#111] opened 2022-08-04 17:15 UTC
I'm munging a bunch of OpenGWAS data with MSS, and i noticed that the number of variants dropped due to being non-biallelic was quite high (hundreds of thousands-millions). In some cases, up to half the original SNPs are being dropped because they’re non-biallelic.

## Reprex 

```R
gwas_paths <- MungeSumstats::import_sumstats(
  ids = "ieu-a-8", 
  save_dir = here::here("data/GWAS_sumstats"), 
  nThread = 30, # >30 causes issues with read_vcf_parallel
  parallel_across_ids = FALSE, 
  force_new_vcf = FALSE,
  force_new = FALSE,
  vcf_download = TRUE,
  vcf_dir = here::here("data/VCFs"), 
  #### Record logs
  log_folder_ind = TRUE,
  log_mungesumstats_msgs = TRUE,
  ) 
```
### Example 1: ieu-a-8

In this case, a GWAS with 2.4M variants had 1.2M+ non-bilallelic variants removed:
[mss.txt](https://github.com/neurogenomics/MungeSumstats/files/9261829/mss.txt)

### Example 2: Vuckovic2020

Here’s another where 5M/44M variant were considered non-biallelic:
[mss_vuckovic.txt](https://github.com/neurogenomics/MungeSumstats/files/9261831/mss_vuckovic.txt)

## Literature

- [Campbell2016](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4752396/): Notes that even at the higher estimates we’d only expect multi-allelic sites in 3% of SNPs.
- [Phillips2020](https://www.sciencedirect.com/science/article/pii/S187249732030003X): Found only 0.3% of SNPs in 1KG Phase 3 were tri-allelic.
- [Phillips2016](https://pubmed.ncbi.nlm.nih.gov/26209763/): Found only 961 SNPs in 1KG Phase 3 were tetra-allelic.

## Possible explanations

1. MSS is over-attributing multi-allelic status to variants somehow, 
2. The updates to Bioc's dbSNP ref contains lots more reported multi-allelic sites that in previous versions.
3. Something went awry when making the latest Bioc dbSNP dataset.
4. This is the true number of multi-allelic variants and it is far above the estimates from single-cohort studies (e.g. 1KGp3) bc it incorporates info from across many different datasets.

## To do 
- [x] Double check relevant MSS code. @Al-Murphy 
- [x] Compare number of multi-allelic SNPs in old vs new Bioc dbSNP datasets. @Al-Murphy 
- [ ] Check the %/# non-ballelic variants that were filtered in previous versions of MSS. @bschilder 
- [x] Check the %/# non-ballelic variants that were filtered using the latest version of MSS. @bschilder

**Comment by bschilder** [comment] 2022-08-04 19:23
> @bschilder can you add the top 10 or so rows of the log file of the dropped non-biallelic SNPs from Example 1: ieu-a-8 or Example 2: Vuckovic2020?

Sure! 
- [ieu-a-8.snp_bi_allelic.txt](https://github.com/neurogenomics/MungeSumstats/files/9262711/ieu-a-8.snp_bi_allelic.txt)
- [Vuckovic2020.snp_bi_allelic.txt](https://github.com/neurogenomics/MungeSumstats/files/9262706/Vuckovic2020.snp_bi_allelic.txt)

**Comment by Al-Murphy** [comment] 2022-08-04 19:27
I have checked MSS code and it seems to work as I suspect it to, it appears that there are now just a lot more alternative alleles in bioconductor's dbSNP 155 vs 144. See the example below where dbSNP 144 finds no non-biallelic but 155 finds 48 from a total of 93:

```
#MSS showing a lot is non-biallelic dbSNP 155 vs 144
sumstats_dt <- MungeSumstats::formatted_example()
rsids <- MungeSumstats:::load_ref_genome_data(snps = sumstats_dt$SNP,
                                              ref_genome = "GRCH38",
                                              dbSNP=144)
rsids155 <- MungeSumstats:::load_ref_genome_data(snps = sumstats_dt$SNP,
                                                 ref_genome = "GRCH38",
                                                 dbSNP=155)

# get chars for SNPs not bi/tri allelic
# or strand ambig from IUPAC_CODE_MAP
nonambig_IUPAC_CODE_MAP <-
  names(Biostrings::IUPAC_CODE_MAP[nchar(
    Biostrings::IUPAC_CODE_MAP
  ) < 3])

data.table::setkey(rsids, SNP)
data.table::setkey(rsids155, SNP)
bad_ids <- rsids[!alleles_as_ambig %in% nonambig_IUPAC_CODE_MAP]
print(nrow(bad_ids))
bad_ids155 <- rsids155[!alleles_as_ambig %in% nonambig_IUPAC_CODE_MAP]
print(nrow(bad_ids155))
print(bad_ids155)
```

There is no github page for [bioconductor's dbSNP 155](https://bioconductor.org/packages/release/data/annotation/html/SNPlocs.Hsapiens.dbSNP155.GRCh38.html) so I'll just message Herve to ask his opinion on what's going on

**Comment by bschilder** [comment] 2022-08-04 19:34
> I have checked MSS code and it seems to work as I suspect it to, it appears that there are now just a lot more alternative alleles in bioconductor's dbSNP 155 vs 144. See the example below where dbSNP 144 finds no non-biallelic but 155 finds 48 from a total of 93:

Ok, well that at least narrows thing down. Thanks!

> There is no github page for [bioconductor's dbSNP 155](https://bioconductor.org/packages/release/data/annotation/html/SNPlocs.Hsapiens.dbSNP155.GRCh38.html) so I'll just message Herve to ask his opinion on what's going on

That would be great, thanks!

**Comment by Al-Murphy** [comment] 2022-08-04 20:40
I randomly picked 3 SNPs from my example code above and checked them in NCBI dbSNP online portal (dbSNP 155) and they all appear to be non-biallelic as described:

[rs9824539](https://www.ncbi.nlm.nih.gov/snp/?term=rs9824539)
[rs9556958](https://www.ncbi.nlm.nih.gov/snp/?term=rs9556958)
[rs7854982](https://www.ncbi.nlm.nih.gov/snp/?term=rs7854982)

I know this is by no means definitive but does seem like it is doing things correctly

**Comment by Al-Murphy** [comment] 2022-08-08 13:06
Had a look into all the RS ID's from dbSNP 144 to check the proportion that are non-biallelic across the dbSNP 155 database and 144. I used an approach separate to MSS to ensure the issue isn't there. This approach was given by @hpages (see below). 

It appears there is just a substantial number more non-biallelic SNPs in 155. This doesn't seem to be a MSS issue and just reflects the changes in the versions.

I'll post about this in https://github.com/hpages/SNPlocsForge in case anyone else has further insight but I believe the field's focus on biallelic SNPs may need to change as the number of non-biallelic SNPs increase. ~24% is a large proportion of SNPs to exclude.

I'll leave this issue open for now for others to see.

```
#wget "http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/snp144.txt.gz"
#gunzip snp144.txt.gz
snps <- limma::read.columns("~/Downloads/snp144.txt", 
                            required.col=c("rs775809821"))$rs775809821
#missing header so add in SNP
snps <- c("rs775809821",snps)

library(BSgenome)
extractAlleles <- function(rsids, dbSNP, ref_genome="GRCh38")
{
  pkgname <- paste0("SNPlocs.Hsapiens.dbSNP", dbSNP, ".", ref_genome)
  pkgenv <- loadNamespace(pkgname)
  snplocs <- get(pkgname, envir=pkgenv, inherits=FALSE)
  snps <- snpsById(snplocs, rsids, ifnotfound="drop")
  unname(setNames(IUPAC_CODE_MAP[mcols(snps)$alleles_as_ambig],
                  mcols(snps)$RefSNP_id)[rsids])
}

dbSNP144_alleles <- extractAlleles(snps, 144)
dbSNP155_alleles <- extractAlleles(snps, 155)
alleles <- data.frame(rsid=snps, dbSNP144_alleles, dbSNP155_alleles)
alleles <- data.table::setDT(alleles)
#remove where alleles missing for either
alleles <- alleles[!(is.na(dbSNP144_alleles) | is.na(dbSNP155_alleles))]
alleles[nchar(dbSNP144_alleles)==2 & nchar(dbSNP155_alleles)==2,
        match:="both biallelic"]
alleles[nchar(dbSNP144_alleles)>2 & nchar(dbSNP155_alleles)>2,
        match:="both non-biallelic"]
alleles[nchar(dbSNP144_alleles)>2 & nchar(dbSNP155_alleles)==2,
        match:="dbSNP 144 non-biallelic"]
alleles[nchar(dbSNP144_alleles)==2 & nchar(dbSNP155_alleles)>2,
        match:="dbSNP 155 non-biallelic"]
summ <- alleles[,.N,by=match]
summ[,prop:=N/sum(summ$N)]
#> summ
#match         N         prop
#1:          both biallelic 100605258 0.7427438640
#2: dbSNP 155 non-biallelic  32266661 0.2382168183
#3:      both non-biallelic   2565775 0.0189424855
#4: dbSNP 144 non-biallelic     13116 0.0000968322

```

**Comment by Al-Murphy** [comment] 2022-08-12 07:24
Posted on Biostars about this issue and got some replies too - https://www.biostars.org/p/9534249/#9534468

Generally, seems like people agree that the observed numbers are true

**Comment by ilevantis** [comment] 2022-09-02 15:38
I'm not conviced that dropping anything marked as multi-allelic in dbSNP is a sensible idea. As I understand it, the reasons for removing multi-allelic SNPs could be the following:
1. The downstream tool cannot handle a table row defining a SNP with multiple alternate alleles.
2. The downstream tool assumes all input is bi-allelic and calculates things such as allele frequency as `1 - effect_allele_frq` or uses a statistical model that would have assumptions violated by multi-allelic variants.

For point 1, it could well be valid to simply split the row into two rows f.e.g:
```
POS   REF   ALT
123   A     G
123   A     T
```
(Although in some cases having duplicated genomic location could be an issue.)

For point 2, bi-allelic vs multi-allelic should only matter within the dataset. If a study sample includes only two alleles at a genomic location, then it doesn't matter that dbSNP has a third allele on record from a different dataset, as this doesn't affect anything within the study.

**Comment by Al-Murphy** [comment] 2022-09-02 16:00
I think those 2 points highly depend on the downstream analysis use case. I do agree though, I feel dropping non-bi-allelic SNPs is no longer a sensible option given the increasing numbers.

I believe the options of splitting multi-allelic SNPs where the ALT contains more than one alternative allele to multiple rows and removing multi-allelic SNPs where more than one of the alternative alleles are in the sumstats itself are both very sensible. If you would like to have a go at adding functionality to do these to MSS as alternative multi-allelic approaches and submit a pull request that would be great! I think it would really benefit the wider community (I'd be happy to add you to the list of contributors too).

**Comment by bschilder** [comment] 2022-09-17 10:47
# OpenGWAS report 

Here's a sampling of 10,863 of the most well-powered GWAS in OpenGWAS.

## Absolute number 

![nonbiallelic](https://user-images.githubusercontent.com/34280215/190852758-d3ec0638-16b0-4ac6-8471-68ffd4a02030.png)

The number of non-biallelic SNPs dropped ranged from 177 to 8.6 million (with a mean of 1.1 million) for a single GWAS.

![Screenshot 2022-09-17 at 11 42 33](https://user-images.githubusercontent.com/34280215/190852811-8e6ff610-59d5-45bb-a867-63be358d3a80.png)

## Percent 

As a percentage of the total SNPs in each GWAS to begin with:

![plot_zoom_png](https://user-images.githubusercontent.com/34280215/190852850-6dddba6e-a14b-49de-bccd-c7e2bdf479c7.png)
![Screenshot 2022-09-17 at 11 45 54](https://user-images.githubusercontent.com/34280215/190852876-99ea3b7d-6c0a-4907-b1d5-61a15d82f88c.png)

The average percentage of non-biallelic SNPS was 47%, ranging from ~0 to 63%.

**Comment by Lloyd-LiuSiyi** [comment] 2022-11-23 05:31
Hi Murphy! I seem to face the same situation that a huge number of SNPs get removed for being non-biallelic. I was wondering if there is now an argument I can specify to keep the non-biallelic SNPs. Thanks in advance!

**Comment by Lloyd-LiuSiyi** [comment] 2022-11-23 05:44
Sorry for my ignorance, non-biallelic SNPs can be kept by specifying the `bi_allelic_filter` argument.

**Comment by cfbeuchel** [comment] 2024-02-02 14:17
Hi!

I'm, sorry for writing in this old issue, but I am looking for a solution for this and saw the conversation in the [SNPlocsForge Repo](https://github.com/hpages/SNPlocsForge/issues/1), which was concluded some time ago, but I failed to understand the solution. I have a high number of non bi-allelic SNP dropped when using MungeSumtats, with all up-to-date packages from Bioconductor 3.18? Is the solution that this is simply due to higher coverage in more up-to-date dbSNP versions and the way forward would be to drop the few individuals with the 3+rd allele instead of removing the whole SNP?

Thanks for your help and the great work on this package!

Cheers!

**Comment by Al-Murphy** [comment] 2024-02-02 14:49
Hey,

>using MungeSumtats, with all up-to-date packages from Bioconductor 3.18
Yes, this is the latest release version of MSS.

>Is the solution that this is simply due to higher coverage in more up-to-date dbSNP versions and the way forward would be to drop the few individuals with the 3+rd allele instead of removing the whole SNP?

That's one solution, another one would be to keep non-bi-allelic SNPs (set `bi_allelic_filter=FALSE` when running `format_sumstats()`) - note this affects FRQ calculations if they need to be flipped etc. It really depends on what you plan on doing with the sumstats, some downstream tools like LDSC for example, will remove non-bi-allelic SNPs anyway (leaving just HapMap3 SNPs). Personally, I think you should keep non-bi-allelic SNPs unless you have a good reason to remove them.

Cheers,
Alan.

**Comment by Al-Murphy** [comment] 2024-08-15 13:16
Closing as I believe we have looked into this enough at this stage and have a work around in place (set `bi_allelic_filter=FALSE` in `format_sumstats()`)

**Closed by Al-Murphy** 2024-08-15 13:16 UTC
